### ISSUE TITLE
 Throws uncaught error when image does not have embeded text

### ISSUE THREAD

**Issue by PotOfCoffee2Go** [mykeels/steganography#1]
An example of doing a `digUp()` on an image that has no embeded text. Note that a password was given in  `pw`  - the wrong image was given (ie: one that was not previously `embed()`):

```js
      ...
    console.log('got here!!!!');
    try {
    const text = await digUp(imagePath, pw);
    } catch(err) {console.log('error!!!')}
    console.log('got here too!!!!');
     ...
```
Results in an uncaught error 
```
got here!!!!
internal/crypto/cipher.js:103
    this[kHandle].initiv(cipher, credential, iv, authTagLength);
                  ^

Error: Invalid IV length
    at Decipheriv.createCipherBase (internal/crypto/cipher.js:103:19)
    at Decipheriv.createCipherWithIV (internal/crypto/cipher.js:121:20)
    at new Decipheriv (internal/crypto/cipher.js:262:22)
    at Object.createDecipheriv (crypto.js:131:10)
    at decrypt (/home/poc2go/Documents/stg/node_modules/@mykeels/steganography/src/encrypt-decrypt.js:19:27)
    at Jimp.<anonymous> (/home/poc2go/Documents/stg/node_modules/@mykeels/steganography/src/index.js:35:48)
    at Timeout._onTimeout (/home/poc2go/Documents/stg/node_modules/@jimp/core/dist/index.js:354:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```
This is happening due to the try block in `src/index.js` line 35 needs to include the line above it. The call to `decrypt()` is what throws. A password was given so the `decrypt()` runs even though the image itself has no text.
**src/indexjs - lines 34 and 35**
```js
        const modifiedPayloadText = password ? decrypt(payloadText, password) : payloadText;
        try {
```
Also that change will require the console.log on line 51 to be removed or changed as `modifiedPayloadText` will not exist.
```js
          console.log({ modifiedPayloadText });
```
> I removed line 51 and moved the `try {` up a line allowing the `reject(new Error('Could not decrypt message'));` to execute when the `decrypt()` at line 34 throws - which is adequate for my needs.

Happy to give a PR with my change - but thought you might want to implement differently or a catch with a more meaningful message.

Thanks for sharing the module :+1:

**Comment by mykeels** [comment]
Hi @PotOfCoffee2Go 

Thanks for this. Please make the PR, and I'm happy to merge.
